import React from "react";
import { UnstyledPageContainer } from "../../components/containers/UnstyledPageContainer";
import { PrismLight as SyntaxHighlighter } from 'react-syntax-highlighter';
import scss from 'react-syntax-highlighter/dist/esm/languages/prism/scss';
import darkSyntax from 'react-syntax-highlighter/dist/esm/styles/prism/vsc-dark-plus';
import { FadeInWhenVisible } from "../../components/animation/fadeInWhenVisible";
import { Link } from "react-router";

SyntaxHighlighter.registerLanguage('scss', scss);


export const Glassmorphism = (props: React.HTMLAttributes<HTMLDivElement>) => {
    return <UnstyledPageContainer {...props} id="ds-glassmorphism" className="text-black">
        <section id="hero" className="d-flex flex-column align-items-center justify-content-center position-relative">
            <div id="hero-text" className="glass-light mac-icons position-absolute text-center d-flex flex-column justify-content-center">
                <h1>Glassmorphism</h1>
                <h2>The "frosted glass" aesthetic</h2>
            </div>
        </section>
        <section id="about" className="w-100 d-flex flex-column justify-content-center align-items-center py-10 gap-4 position-relative">
            <FadeInWhenVisible className="container-lg row row-cols-1 row-cols-sm-2 g-4">
                <div className="col col-lg-4">
                    <div className="glass-dark p-5 h-100">
                        <h2>About</h2>
                        <p>Glassmorphism is a modern web design style characterised by translucent, blurred elements that recreate the effect of frosted glass. These elements are often overlayed over smooth background gradients to emphasise the depth and dimension of the interface.</p>
                    </div>
                </div>
                <div className="col col-lg-8">
                    <div className="glass-light p-5 h-100">
                        <h2>Features</h2>
                        <p>The glass texture is generated by the interplay of transparency, background blur, and border effects. Transparency allows the background to show through, the blur enables elements to exist legibly on top, and the border improves separation and enhances the illusion of depth.</p>
                        <p>Recent developments in the glassmorphism style (notably via Apple Tahoe) use a dynamic border that adapts its colour and lightness in response to the surrounding environment, even going so far as to create the illusion of refraction around corners.</p>
                    </div>
                </div>
            </FadeInWhenVisible>
            <FadeInWhenVisible className="container-lg row row-cols-1 g-4">
                <div className="col">
                    <div className="glass-light p-5 h-100">
                        <h2>History</h2>
                        <p>Mimicking the effect of glass is not new in digital design – Windows Vista's Aero interface from 2007 brought the effect to the mainstream. The style then developed as a form of skeuomorphism, popular at the time as a way to make digital interfaces feel more tangible. This took the form of harsh shadows and glossy highlights.</p>
                        <p>What separates modern glassmorphism from these earlier attempts is more careful consideration of the background: vivid colours or images with smooth gradients replace the harsher effects seen prior.</p>
                    </div>
                </div>
            </FadeInWhenVisible>
            <FadeInWhenVisible className="container-lg row row-cols-1 row-cols-md-2 g-4">
                <div className="col">
                    <div className="glass-light p-5 h-100">
                        <h2>When to use</h2>
                        <p>Glassmorphism as it is now represents the frontier of modern UI design. New, tech-focused apps match this to keep in style with e.g. MacOS Tahoe and Windows 11, both of which heavily employ this design style. Given the recency of the trend, it has a heavy association with AI-powered or vibecoded apps.</p>
                    </div>
                </div>
                <div className="col">
                    <div className="glass-dark p-5 h-100">
                        <h2>When to avoid</h2>
                        <p>Glassmorphism suffers a <i>major</i> problem in its accessibility. Any amount of background transparency reduces the contrast between the text and its background, which significantly impacts legibility. Depending on the implementation, certain effects can also be expensive to compute, slowing pages down for users on low-end devices.</p>
                    </div>
                </div>
            </FadeInWhenVisible>
        </section>

        {/* achieving this in CSS */}
        <section id="css-implementation" className="w-100 d-flex flex-column justify-content-center align-items-center py-10 gap-4 position-relative text-white">
            <FadeInWhenVisible className="container-lg row row-cols-1 g-4">
                <h2 className="text-shadow">CSS Implementation</h2>
                <p>The simplest way to achieve the 3 key properties – transparency, blur, border – is with a few lines of CSS.</p>
                <div className="col">
                    <SyntaxHighlighter language={"scss"} style={darkSyntax}>
{`.glass {
  background: rgba(255, 255, 255, 0.1);         // transparency
  backdrop-filter: blur(6px);                   // blur
  border: 2px solid rgba(255, 255, 255, 0.2);   // border
  border-radius: 32px;
}`}
                    </SyntaxHighlighter>
                </div>
                <p>This can be extended in a number of ways. Adding a box shadow enhances the depth and realism of the glass; replacing the background with a subtle gradient helps sell the "sheen"; and similarly replacing the border with a gradient* can recreate a feeling of refraction without custom code.</p>
                <p>*gradient borders that respect <code>border-radius</code> are not easy! <code>border-image</code> does not support border-radius, so my solution used for the cards above was to use a pseudo-element with a background gradient and a composite exclusion mask that only "selects" the border area.</p>
            </FadeInWhenVisible>
        </section>
        <section id="examples" className="my-8">
            <FadeInWhenVisible className="container-lg">
                <h2 className="text-white mb-5 text-shadow">Examples</h2>
                <div className="container-lg row row-cols-1 row-cols-md-2 g-4 align-items-center">
                    <div className="col">
                        <div className="glass-light p-5 scale-hover">
                            <img src="/assets/design-styles/glassmorphism/apple.webp" alt="The Adobe app on macOS." className="img-fluid rounded-4" />
                            <div className="font-size-small mt-1">The Adobe app on macOS. Example of glassmorphism in Tahoe.</div>
                        </div>
                    </div>
                    <div className="col">
                        <div className="glass-light p-5 scale-hover">
                            <img src="/assets/design-styles/glassmorphism/lumina.webp" alt="Lumina AI app." className="img-fluid rounded-4" />
                            <div className="font-size-small mt-1">Lumina app, an AI-focused standalone app built with glassmorphism.</div>
                        </div>
                    </div>
                </div>
            </FadeInWhenVisible>
        </section>
        <section id="further-reading" className="text-center w-100 pt-8 mb-10">
            <FadeInWhenVisible className="container-lg">
                <div className="glass-light py-8 scale-hover">
                    <h2>Like this and want more?</h2>
                    <Link to="/design-styles"><b>Check out my other design style pages!</b></Link>
                </div>
            </FadeInWhenVisible>
        </section>
    </UnstyledPageContainer>;
};
