name: actions
on: [push]
jobs:
    cleanup:
        runs-on: ubuntu-latest
        permissions: write-all

        steps:
          - name: Delete Deployment
            uses: strumwolf/delete-deployment-environment@v3
            with:
              token: ${{ secrets.GITHUB_TOKEN }}
              environment: github-pages
              onlyRemoveDeployments: true